/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Material Design 3 tokens from Scholar's Sketchbook ──
        "surface":                   "#fcf9f8",
        "surface-dim":               "#dcd9d9",
        "surface-bright":            "#fcf9f8",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f6f3f2",
        "surface-container":         "#f0eded",
        "surface-container-high":    "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface":                "#1c1b1b",
        "on-surface-variant":        "#414751",
        "inverse-surface":           "#313030",
        "inverse-on-surface":        "#f3f0ef",
        "outline":                   "#717783",
        "outline-variant":           "#c1c7d3",
        "surface-tint":              "#0060ac",
        "surface-variant":           "#e5e2e1",
        "background":                "#fcf9f8",
        "on-background":             "#1c1b1b",

        "primary":                   "#005da7",
        "on-primary":                "#ffffff",
        "primary-container":         "#2976c7",
        "on-primary-container":      "#fdfcff",
        "inverse-primary":           "#a4c9ff",
        "primary-fixed":             "#d4e3ff",
        "primary-fixed-dim":         "#a4c9ff",
        "on-primary-fixed":          "#001c39",
        "on-primary-fixed-variant":  "#004883",

        "secondary":                 "#835500",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#feae2c",
        "on-secondary-container":    "#6b4500",
        "secondary-fixed":           "#ffddb4",
        "secondary-fixed-dim":       "#ffb955",
        "on-secondary-fixed":        "#291800",
        "on-secondary-fixed-variant":"#633f00",

        "tertiary":                  "#386800",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#498300",
        "on-tertiary-container":     "#f9ffeb",
        "tertiary-fixed":            "#a1fa49",
        "tertiary-fixed-dim":        "#87dc2c",
        "on-tertiary-fixed":         "#0e2000",
        "on-tertiary-fixed-variant": "#2a5000",

        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",

        // ── Semantic aliases for quick access ──
        "paper-cream":  "#FAF6F0",
        "ink-black":    "#1c1b1b",
        "ink-blue":     "#005da7",
        "marker-yellow":"#feae2c",
        "marker-red":   "#ba1a1a",
        "marker-green": "#498300",
      },
      fontFamily: {
        // Design system typography roles
        "display":     ["Bricolage Grotesque", "sans-serif"],
        "headline":    ["Bricolage Grotesque", "sans-serif"],
        "body":        ["Karla", "sans-serif"],
        "mono":        ["JetBrains Mono", "monospace"],
        "marker":      ["Permanent Marker", "cursive"],
        "handwriting": ["Caveat", "cursive"],

        // Named roles matching Stitch config
        "display-lg":  ["Bricolage Grotesque", "sans-serif"],
        "headline-md": ["Bricolage Grotesque", "sans-serif"],
        "headline-sm": ["Bricolage Grotesque", "sans-serif"],
        "body-lg":     ["Karla", "sans-serif"],
        "body-md":     ["Karla", "sans-serif"],
        "source-code": ["JetBrains Mono", "monospace"],
        "label-caps":  ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "800", letterSpacing: "-0.02em" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "source-code": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", fontWeight: "700" }],
      },
      spacing: {
        "unit": "4px",
        "xs":   "4px",
        "sm":   "8px",
        "md":   "16px",
        "lg":   "24px",
        "xl":   "40px",
        "gutter": "16px",
        "margin-mobile":  "16px",
        "margin-desktop": "32px",
      },
      borderRadius: {
        "sketch": "255px 15px 225px 15px / 15px 225px 15px 255px",
      },
      boxShadow: {
        "sketch": "4px 4px 0px #1c1b1b",
        "sketch-sm": "2px 2px 0px #1c1b1b",
      },
    },
  },
  plugins: [],
}
